wandb_version: 1

C:
  desc: null
  value: 1.0
break_ties:
  desc: null
  value: false
cache_size:
  desc: null
  value: 200
class_weight:
  desc: null
  value: null
coef0:
  desc: null
  value: 0.0
decision_function_shape:
  desc: null
  value: ovr
degree:
  desc: null
  value: 3
gamma:
  desc: null
  value: scale
kernel:
  desc: null
  value: rbf
max_iter:
  desc: null
  value: -1
probability:
  desc: null
  value: false
random_state:
  desc: null
  value: null
shrinking:
  desc: null
  value: true
tol:
  desc: null
  value: 0.001
verbose:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690006368.169996
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.15.5
      8:
      - 3
      - 5
test_size:
  desc: null
  value: 0.095
train_len:
  desc: null
  value:
  - 1951
  - 90
test_len:
  desc: null
  value:
  - 488
  - 90
